### ISSUE TITLE
Issue with tensorflow and pmvae

### ISSUE THREAD

**Issue by axelalmet** [ratschlab/pmvae#5]
Hi pmvae developers,

Previously, I had been using pmvae for my own data successfully and to great effect. However, recently, when I have tried to run the following code, which is essentially the same as `demo.ipynb`:

```
# Set the gene annotations
fibroblasts_pmvae.varm['annotations'] = fibroblast_gene_annotations
select_genes = fibroblasts_pmvae.varm['annotations'].sum(1)>0
fibroblasts_pmvae._inplace_subset_var(select_genes)

# Define the training and test set
membership_mask = fibroblasts_pmvae.varm['annotations'].astype(bool).T
trainset, testset = train_test_split(
    fibroblasts_pmvae.X.toarray(),
    test_size=0.25,
    shuffle=True,
    random_state=0,
)

batch_size = 512
trainset = tf.data.Dataset.from_tensor_slices(trainset)
trainset = trainset.shuffle(5 * batch_size).batch(batch_size)

# Define the pmvae model
model = PMVAE(
    membership_mask=membership_mask,
    module_latent_dim=1,
    hidden_layers=[12],
    add_auxiliary_module=True,
    beta=1e-05,
    kernel_initializer='he_uniform',
    bias_initializer='zero',
    activation='elu',
    terms=terms
)

# Define the optimiser
opt = tf.keras.optimizers.Adam(learning_rate=0.001)


# Train the model
history = train(model, opt, trainset, testset, nepochs=1200)

```

I get the following error once I run `train`:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/t8/0xg2c3251gg7ycfqvz5g4yxr0000gn/T/ipykernel_10448/648582890.py in <module>
      1 # This should take ~1hr on GPU (first iter takes ~1m)
----> 2 history = train(model, opt, trainset, testset, nepochs=1200)

/usr/local/lib/python3.8/site-packages/pmvae-0.1.0-py3.8.egg/pmvae/train.py in train(model, opt, trainset, testset, nepochs, debug)

/usr/local/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py in error_handler(*args, **kwargs)
    151     except Exception as e:
    152       filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153       raise e.with_traceback(filtered_tb) from None
    154     finally:
    155       del filtered_tb

/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1127     try:
   1128       if autograph:
-> 1129         from tensorflow.python import autograph  # pylint: disable=g-import-not-at-top
   1130         _, original_func = tf_decorator.unwrap(python_func)
   1131 

AttributeError: in user code:

    File "/usr/local/lib/python3.8/site-packages/pmvae-0.1.0-py3.8.egg/pmvae/train.py", line 55, in compute_apply_gradients  *
        loss = pmvae_loss(model, x)
    File "/usr/local/lib/python3.8/site-packages/pmvae-0.1.0-py3.8.egg/pmvae/train.py", line 21, in pmvae_loss  *
        outputs = model(inputs)
    File "/usr/local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
        raise e.with_traceback(filtered_tb) from None

    AttributeError: Exception encountered when calling layer "pmvae_1" (type PMVAE).
    
    in user code:
    
        File "/usr/local/lib/python3.8/site-packages/pmvae-0.1.0-py3.8.egg/pmvae/model.py", line 94, in call  *
            mu, logvar = self.encode(x, **kwargs)
        File "/usr/local/lib/python3.8/site-packages/pmvae-0.1.0-py3.8.egg/pmvae/model.py", line 76, in encode  *
            params = self.encoder_net(x, **kwargs)
        File "/usr/local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
    
        AttributeError: Exception encountered when calling layer "masked_layer_4" (type MaskedLayer).
        
        in user code:
        
            File "/usr/local/lib/python3.8/site-packages/pmvae-0.1.0-py3.8.egg/pmvae/utils.py", line 123, in call  *
                self.activation,
        
            AttributeError: module 'tensorflow.python.keras.layers.ops' has no attribute 'core'
        
        
        Call arguments received:
          • inputs=tf.Tensor(shape=(512, 1068), dtype=float32)
    
    
    Call arguments received:
      • x=tf.Tensor(shape=(512, 1068), dtype=float32)
      • kwargs={'training': 'None'}
```

Is there an easy fix for this? Thank you for your package and help!

Best wishes,
Axel.

**Comment by nrosed** [comment]
Hi Axel! Thanks for using pmVAE we will look into it and get back to you shortly!

**Comment by stefangstark** [comment]
Looks like a tensorflow update removed a function we used. Are you able to downgrade to 2.3? Meanwhile we can look into updating

**Comment by axelalmet** [comment]
Hi @stefangstark, 

Thank you and @nrosed for getting back to me! I'll look into seeing if I can downgrade down to tensorflow 2.3. From memory, there's a package I use that requires at least >2.4, but I may try and get around this by using a virtual environment with tensorflow 2.3 only. 

I'm also happy to wait, if you think it won't take too long to update pmVAE!

Best wishes,
Axel.

**Comment by stefangstark** [comment]
Hi axel, 

I've removed the dependency on the outdated tf code. It should work on most tf versions now. Let us know if you have any further questions!

Best,
Stefan

**Comment by axelalmet** [comment]
Hi Stefan,

Very sorry for the late reply, but pmVAE works again! Thank you so much for your help.

Best wishes,
Axel.
